//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlgorithmMistake_tbl
    {
        public int id { get; set; }
        public string word { get; set; }
        public int oldSubject { get; set; }
        public int newSubject { get; set; }
        public int AmountOfMistakes { get; set; }
    
        public virtual Subject_tbl Subject_tbl { get; set; }
        public virtual Subject_tbl Subject_tbl1 { get; set; }
    }
}
