//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForSubject_tbl
    {
        public int id { get; set; }
        public int contactManID { get; set; }
        public int subjectId { get; set; }
        public double contactWeight { get; set; }
    
        public virtual ContactMan_tbl ContactMan_tbl { get; set; }
        public virtual Subject_tbl Subject_tbl { get; set; }
    }
}
