//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email_tbl()
        {
            this.UpdateKeySentence_tbl = new HashSet<UpdateKeySentence_tbl>();
            this.UpdateKeySentenceForSemilar_tbl = new HashSet<UpdateKeySentenceForSemilar_tbl>();
            this.UpdateSubject_tbl = new HashSet<UpdateSubject_tbl>();
        }
    
        public int mailID { get; set; }
        public string IdInOutLook { get; set; }
        public int toUserId { get; set; }
        public string fromName { get; set; }
        public string fromAddressMail { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public System.DateTime dateReceived { get; set; }
        public Nullable<int> subjectMail { get; set; }
        public string RelatedSentence { get; set; }
    
        public virtual Subject_tbl Subject_tbl { get; set; }
        public virtual User_tbl User_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateKeySentence_tbl> UpdateKeySentence_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateKeySentenceForSemilar_tbl> UpdateKeySentenceForSemilar_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateSubject_tbl> UpdateSubject_tbl { get; set; }
    }
}
