//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextClassificationProjectEntities : DbContext
    {
        public TextClassificationProjectEntities()
            : base("name=TextClassificationProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlgorithmMistake_tbl> AlgorithmMistake_tbl { get; set; }
        public virtual DbSet<BaseWord_tbl> BaseWord_tbl { get; set; }
        public virtual DbSet<ContactForSubject_tbl> ContactForSubject_tbl { get; set; }
        public virtual DbSet<ContactMan_tbl> ContactMan_tbl { get; set; }
        public virtual DbSet<Email_tbl> Email_tbl { get; set; }
        public virtual DbSet<Subject_tbl> Subject_tbl { get; set; }
        public virtual DbSet<UpdateKeySentence_tbl> UpdateKeySentence_tbl { get; set; }
        public virtual DbSet<UpdateKeySentenceForSemilar_tbl> UpdateKeySentenceForSemilar_tbl { get; set; }
        public virtual DbSet<UpdateSubject_tbl> UpdateSubject_tbl { get; set; }
        public virtual DbSet<User_tbl> User_tbl { get; set; }
        public virtual DbSet<Word_tbl> Word_tbl { get; set; }
        public virtual DbSet<WordForSubject_tbl> WordForSubject_tbl { get; set; }
    }
}
