//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateKeySentenceForSemilar_tbl
    {
        public int id { get; set; }
        public int mailID { get; set; }
        public int subjectId { get; set; }
        public string word { get; set; }
        public double commonWeight { get; set; }
        public int commonAmount { get; set; }
        public double specialWeight { get; set; }
        public int specialAmount { get; set; }
    
        public virtual Email_tbl Email_tbl { get; set; }
        public virtual Subject_tbl Subject_tbl { get; set; }
    }
}
