//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordForSubject_tbl
    {
        public int id { get; set; }
        public int subjectId { get; set; }
        public int wordId { get; set; }
        public double wordWeight { get; set; }
        public bool isCommon { get; set; }
    
        public virtual Subject_tbl Subject_tbl { get; set; }
        public virtual Word_tbl Word_tbl { get; set; }
    }
}
